// <auto-generated />
using System;
using Ehgiz.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ehgiz.DAL.Migrations
{
    [DbContext(typeof(EhgizDbContext))]
    [Migration("20260607150705_change-id-to-int")]
    partial class changeidtoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ehgiz.DAL.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RenterId");

                    b.HasIndex("ToolId");

                    b.ToTable("Bookings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            RenterId = 2,
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            ToolId = 1,
                            TotalPrice = 225m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            RenterId = 2,
                            StartDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            ToolId = 3,
                            TotalPrice = 150m
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Drills, saws, sanders, and other electric tools.",
                            ImageUrl = "https://cdn.ehgiz.com/categories/power-tools.jpg",
                            IsActive = true,
                            Name = "Power Tools"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Lawn mowers, trimmers, and garden equipment.",
                            ImageUrl = "https://cdn.ehgiz.com/categories/gardening.jpg",
                            IsActive = true,
                            Name = "Gardening"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ladders, scaffolding, and construction gear.",
                            ImageUrl = "https://cdn.ehgiz.com/categories/construction.jpg",
                            IsActive = true,
                            Name = "Construction"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pressure washers, vacuums, and cleaning machines.",
                            ImageUrl = "https://cdn.ehgiz.com/categories/cleaning.jpg",
                            IsActive = true,
                            Name = "Cleaning Equipment"
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("User1Id")
                        .HasColumnType("int");

                    b.Property<int>("User2Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Conversations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UpdatedAt = new DateTime(2026, 3, 9, 16, 0, 0, 0, DateTimeKind.Utc),
                            User1Id = 1,
                            User2Id = 2
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.IssueReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ReporterId");

                    b.ToTable("IssueReports", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 2,
                            CreatedAt = new DateTime(2026, 3, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "One of the safety locks on the ladder feels loose.",
                            ReporterId = 2,
                            Status = "Open",
                            Title = "Ladder lock issue"
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hi Ahmad, is the drill still available next week?",
                            ConversationId = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            SenderId = 2,
                            Status = "Read"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Yes, it is available. Let me know your dates.",
                            ConversationId = 1,
                            CreatedAt = new DateTime(2026, 1, 20, 9, 15, 0, 0, DateTimeKind.Utc),
                            SenderId = 1,
                            Status = "Read"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Can I pick up the ladder on March 10th?",
                            ConversationId = 1,
                            CreatedAt = new DateTime(2026, 3, 8, 11, 0, 0, 0, DateTimeKind.Utc),
                            SenderId = 2,
                            Status = "Delivered"
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Your booking for Bosch Professional Drill has been completed.",
                            CreatedAt = new DateTime(2026, 2, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            Type = "BookingUpdate",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "Payment of 150 EGP is held in escrow for your ladder booking.",
                            CreatedAt = new DateTime(2026, 3, 9, 14, 35, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "PaymentUpdate",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "You have a new message from Sara Mohamed.",
                            CreatedAt = new DateTime(2026, 3, 8, 11, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Type = "NewMessage",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("EscrowStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 225m,
                            BookingId = 1,
                            EscrowStatus = "Released",
                            PaidAt = new DateTime(2026, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "CreditCard",
                            PaymentStatus = "Completed"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 150m,
                            BookingId = 2,
                            EscrowStatus = "Held",
                            PaidAt = new DateTime(2026, 3, 9, 14, 30, 0, 0, DateTimeKind.Utc),
                            PaymentMethod = "Wallet",
                            PaymentStatus = "Completed"
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            Comment = "Excellent drill, worked perfectly for my home project.",
                            CreatedAt = new DateTime(2026, 2, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("InsurancePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Tools", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "18V cordless drill with two batteries and charger.",
                            InsurancePrice = 150m,
                            IsAvailable = true,
                            Location = "Cairo, Maadi",
                            Name = "Bosch Professional Drill",
                            OwnerId = 1,
                            PricePerDay = 75m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Condition = "Excellent",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "1600W electric lawn mower suitable for medium gardens.",
                            InsurancePrice = 200m,
                            IsAvailable = true,
                            Location = "Cairo, Maadi",
                            Name = "Electric Lawn Mower",
                            OwnerId = 1,
                            PricePerDay = 90m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "6-meter extension ladder with safety locks.",
                            InsurancePrice = 100m,
                            IsAvailable = false,
                            Location = "Alexandria, Smouha",
                            Name = "Aluminum Extension Ladder",
                            OwnerId = 3,
                            PricePerDay = 50m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Condition = "Good",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "2000 PSI pressure washer for outdoor cleaning.",
                            InsurancePrice = 120m,
                            IsAvailable = true,
                            Location = "Alexandria, Smouha",
                            Name = "Pressure Washer",
                            OwnerId = 3,
                            PricePerDay = 65m,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.ToolImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToolId");

                    b.ToTable("ToolImages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://cdn.ehgiz.com/tools/drill-1.jpg",
                            ToolId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://cdn.ehgiz.com/tools/drill-2.jpg",
                            ToolId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://cdn.ehgiz.com/tools/mower-1.jpg",
                            ToolId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://cdn.ehgiz.com/tools/ladder-1.jpg",
                            ToolId = 3
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://cdn.ehgiz.com/tools/washer-1.jpg",
                            ToolId = 4
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Nile Street",
                            City = "Cairo",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmad.hassan@ehgiz.com",
                            FullName = "Ahmad Hassan",
                            IsActive = true,
                            PhoneNumber = "+201001234567",
                            ProfileImageUrl = "https://cdn.ehgiz.com/users/ahmad.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Garden City",
                            City = "Giza",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.mohamed@ehgiz.com",
                            FullName = "Sara Mohamed",
                            IsActive = true,
                            PhoneNumber = "+201076543210",
                            ProfileImageUrl = "https://cdn.ehgiz.com/users/sara.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Address = "8 Alexandria Road",
                            City = "Alexandria",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar.ali@ehgiz.com",
                            FullName = "Omar Ali",
                            IsActive = true,
                            PhoneNumber = "+201112223344",
                            ProfileImageUrl = "https://cdn.ehgiz.com/users/omar.jpg"
                        });
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Booking", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.User", "Renter")
                        .WithMany("Bookings")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ehgiz.DAL.Entities.Tool", "Tool")
                        .WithMany("Bookings")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Renter");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Conversation", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.User", "User1")
                        .WithMany("ConversationsAsUser1")
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ehgiz.DAL.Entities.User", "User2")
                        .WithMany("ConversationsAsUser2")
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.IssueReport", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.Booking", "Booking")
                        .WithMany("IssueReports")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ehgiz.DAL.Entities.User", "Reporter")
                        .WithMany("IssueReports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Message", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ehgiz.DAL.Entities.User", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Notification", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Payment", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("Ehgiz.DAL.Entities.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Review", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.Booking", "Booking")
                        .WithMany("Reviews")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Tool", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.Category", "Category")
                        .WithMany("Tools")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ehgiz.DAL.Entities.User", "Owner")
                        .WithMany("OwnedTools")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.ToolImage", b =>
                {
                    b.HasOne("Ehgiz.DAL.Entities.Tool", "Tool")
                        .WithMany("Images")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Booking", b =>
                {
                    b.Navigation("IssueReports");

                    b.Navigation("Payment");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Category", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.Tool", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Ehgiz.DAL.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ConversationsAsUser1");

                    b.Navigation("ConversationsAsUser2");

                    b.Navigation("IssueReports");

                    b.Navigation("Notifications");

                    b.Navigation("OwnedTools");

                    b.Navigation("SentMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
